-- Bài 1️: Sử dụng cơ sở dữ liệu QLDA. Với mỗi câu truy vấn cần thực hiện bằng 2 cách, dùng cast và convert.

-- Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc của các nhân viên
-- ĐỊNH DẠNG DECIMAL(10,2)
-- CAST
SELECT DA.TENDEAN,
       CAST(SUM(PC.THOIGIAN) AS DECIMAL(10,2)) AS TongGio_Decimal_CAST
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

--  CONVERT
SELECT DA.TENDEAN,
       CONVERT(DECIMAL(10,2), SUM(PC.THOIGIAN)) AS TongGio_Decimal_CONVERT
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

-- ĐỊNH DẠNG VARCHAR
-- CAST
SELECT DA.TENDEAN,
       CAST(SUM(PC.THOIGIAN) AS VARCHAR(20)) AS TongGio_Varchar_CAST
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

-- CONVERT
SELECT DA.TENDEAN,
       CONVERT(VARCHAR(20), SUM(PC.THOiGIAN)) AS TongGio_Varchar_CONVERT
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;


-- Với mỗi phòng ban, liệt kê tên phòng ban và lương trung bình nhân viên
-- ĐỊNH DẠNG DECIMAL(10,2)
-- CAST
SELECT PB.TENPHG,
       CAST(AVG(NV.LUONG) AS DECIMAL(10,2)) AS LuongTB_Decimal_CAST
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG;

-- CONVERT
SELECT PB.TENPHG,
       CONVERT(DECIMAL(10,2), AVG(NV.LUONG)) AS LuongTB_Decimal_CONVERT
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG;

-- ĐỊNH DẠNG VARCHAR
-- Dùng CAST
SELECT PB.TENPHG,
       LEFT(REPLACE(CAST(AVG(NV.LUONG) AS VARCHAR(20)), '.', ','), 20) AS LuongTB_Varchar_CAST
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG;

-- Dùng CONVERT
SELECT PB.TENPHG,
       LEFT(REPLACE(CONVERT(VARCHAR(20), AVG(NV.LUONG)), '.', ','), 20) AS LuongTB_Varchar_CONVERT
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG;

-- BÀI 2: 



